In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("Housepriceprediction.csv")

In [3]:
df.head()

,Id,LotArea,OverallQual,1stFlrSF,GrLivArea,TotRmsAbvGrd,GarageCars,GarageArea,SalePrice
0,1,8450,7,856,1710,8,2,548,208500
1,2,9600,6,1262,1262,6,2,460,181500
2,3,11250,7,920,1786,6,2,608,223500
3,4,9550,7,961,1717,7,3,642,140000
4,5,14260,8,1145,2198,9,3,836,250000

In [4]:
df.shape

(1460, 9)

In [5]:
#Find how many null values are there in feature column
df.isnull().sum()

Id              0
LotArea         0
OverallQual     0
1stFlrSF        0
GrLivArea       0
TotRmsAbvGrd    0
GarageCars      0
GarageArea      0
SalePrice       0
dtype: int64

In [6]:
#Now we are going to drop column Id asit is of no use
df=df.drop(['Id'],axis=1)
print(df.head())
print(df.shape)

   LotArea  OverallQual  1stFlrSF  GrLivArea  TotRmsAbvGrd  GarageCars  \
0     8450            7       856       1710             8           2
1     9600            6      1262       1262             6           2
2    11250            7       920       1786             6           2
3     9550            7       961       1717             7           3
4    14260            8      1145       2198             9           3

   GarageArea  SalePrice
0         548     208500
1         460     181500
2         608     223500
3         642     140000
4         836     250000
(1460, 8)

In [7]:
df['LotArea'].head()

0     8450
1     9600
2    11250
3     9550
4    14260
Name: LotArea, dtype: int64

In [8]:
#Imp. syntax
(df['LotArea']-1).head()

0     8449
1     9599
2    11249
3     9549
4    14259
Name: LotArea, dtype: int64

In [9]:
df['LotArea'].max()

215245

In [10]:
df.columns

Index(['LotArea', 'OverallQual', '1stFlrSF', 'GrLivArea', 'TotRmsAbvGrd',
       'GarageCars', 'GarageArea', 'SalePrice'],
      dtype='object')

In [11]:
for i in df.columns:
    print(df[i].head())

0     8450
1     9600
2    11250
3     9550
4    14260
Name: LotArea, dtype: int64
0    7
1    6
2    7
3    7
4    8
Name: OverallQual, dtype: int64
0     856
1    1262
2     920
3     961
4    1145
Name: 1stFlrSF, dtype: int64
0    1710
1    1262
2    1786
3    1717
4    2198
Name: GrLivArea, dtype: int64
0    8
1    6
2    6
3    7
4    9
Name: TotRmsAbvGrd, dtype: int64
0    2
1    2
2    2
3    3
4    3
Name: GarageCars, dtype: int64
0    548
1    460
2    608
3    642
4    836
Name: GarageArea, dtype: int64
0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

### Normalization
1.Normalization is conducted to make features value ranges from 0 to 1.
          x=[x-min(x)/{max(x)-min(x)}]<br>
2.This whole process is also know as MinMaxScaler

In [12]:
#1st method:-
#By calculating through formula
def normalize(f5):
    result=f5.copy()
    for i in df.columns:
        max_value=df[i].max()
        min_value=df[i].min()
        result[i]=(df[i]-min_value)/(max_value-min_value)
    return result

In [13]:
df1=normalize(df)
df1

,LotArea,OverallQual,1stFlrSF,GrLivArea,TotRmsAbvGrd,GarageCars,GarageArea,SalePrice
0,0.033420,0.666667,0.119780,0.259231,0.500000,0.50,0.386460,0.241078
1,0.038795,0.555556,0.212942,0.174830,0.333333,0.50,0.324401,0.203583
2,0.046507,0.666667,0.134465,0.273549,0.333333,0.50,0.428773,0.261908
3,0.038561,0.666667,0.143873,0.260550,0.416667,0.75,0.452750,0.145952
4,0.060576,0.777778,0.186095,0.351168,0.583333,0.75,0.589563,0.298709
...,...,...,...,...,...,...,...,...
1455,0.030929,0.555556,0.142038,0.247362,0.416667,0.50,0.324401,0.194556
1456,0.055505,0.555556,0.399036,0.327619,0.416667,0.50,0.352609,0.243161
1457,0.036187,0.666667,0.195961,0.377920,0.583333,0.25,0.177715,0.321622
1458,0.039342,0.444444,0.170721,0.140166,0.250000,0.25,0.169252,0.148903
1459,0.040370,0.444444,0.211565,0.173700,0.333333,0.25,0.194640,0.156367

In [14]:
#2nd method:
#By using the library of python
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df2=scaler.fit_transform(df)

In [15]:
#We need to convert array format to dataframe format
df2

array([[0.0334198 , 0.66666667, 0.11977972, ..., 0.5       , 0.3864598 ,
        0.24107763],
       [0.03879502, 0.55555556, 0.21294172, ..., 0.5       , 0.32440056,
        0.20358284],
       [0.04650728, 0.66666667, 0.13446535, ..., 0.5       , 0.42877292,
        0.26190807],
       ...,
       [0.03618687, 0.66666667, 0.19596145, ..., 0.25      , 0.17771509,
        0.321622  ],
       [0.03934189, 0.44444444, 0.17072051, ..., 0.25      , 0.16925247,
        0.14890293],
       [0.04037019, 0.44444444, 0.21156494, ..., 0.25      , 0.19464034,
        0.15636717]])

In [16]:
df2=pd.DataFrame(df2,columns=['LotAera','OverallQual', '1stFlrSF', 'GrLivArea', 'TotRmsAbvGrd',
       'GarageCars', 'GarageArea', 'SalePrice'])

In [17]:
df2

,LotAera,OverallQual,1stFlrSF,GrLivArea,TotRmsAbvGrd,GarageCars,GarageArea,SalePrice
0,0.033420,0.666667,0.119780,0.259231,0.500000,0.50,0.386460,0.241078
1,0.038795,0.555556,0.212942,0.174830,0.333333,0.50,0.324401,0.203583
2,0.046507,0.666667,0.134465,0.273549,0.333333,0.50,0.428773,0.261908
3,0.038561,0.666667,0.143873,0.260550,0.416667,0.75,0.452750,0.145952
4,0.060576,0.777778,0.186095,0.351168,0.583333,0.75,0.589563,0.298709
...,...,...,...,...,...,...,...,...
1455,0.030929,0.555556,0.142038,0.247362,0.416667,0.50,0.324401,0.194556
1456,0.055505,0.555556,0.399036,0.327619,0.416667,0.50,0.352609,0.243161
1457,0.036187,0.666667,0.195961,0.377920,0.583333,0.25,0.177715,0.321622
1458,0.039342,0.444444,0.170721,0.140166,0.250000,0.25,0.169252,0.148903
1459,0.040370,0.444444,0.211565,0.173700,0.333333,0.25,0.194640,0.156367

In [18]:
#Both df1 and df2 is same...

In [19]:
y=df2['SalePrice'].values
x=df2.drop(['SalePrice'],axis=1)
print(y.shape)

(1460,)

In [20]:
x.shape

(1460, 7)

In [21]:
X_train=x[:1000]
Y_train=y[:1000]
X_test=x[1000:]
Y_test=y[1000:]
print(X_train.shape,Y_train.shape)
print(X_test.shape,Y_test.shape)

(1000, 7) (1000,)
(460, 7) (460,)

# Sklearn LinearRegression

In [22]:
from sklearn.linear_model import LinearRegression
linear_regression = LinearRegression()
linear_regression.fit(X_train,Y_train )

LinearRegression()

In [23]:
linear_regression.predict(X_test)

array([ 0.05256727,  0.06611535,  0.32796352,  0.20671707,  0.24678915,
        0.10902359,  0.23708032,  0.04953625,  0.28300887,  0.1122695 ,
        0.12308401,  0.1569166 ,  0.16310674,  0.10771183,  0.15161809,
        0.26628149,  0.2551894 ,  0.27505085,  0.21290885,  0.24519149,
        0.10119321,  0.23110982,  0.11026336,  0.24543575,  0.4592156 ,
        0.11125299,  0.15436659,  0.33200852,  0.12596005,  0.13324869,
        0.13543142,  0.37587591,  0.37394678,  0.30214384,  0.09741419,
        0.05773704,  0.37495069,  0.34003708,  0.0513334 ,  0.02459742,
        0.2184113 ,  0.19048027,  0.20181013,  0.30911548,  0.40493869,
        0.13762001,  0.45817389,  0.13851567,  0.21289195,  0.06829938,
        0.22806158,  0.23172282,  0.23195539,  0.17050331,  0.30610527,
        0.22153166,  0.23632718,  0.26463765,  0.37904776,  0.22441845,
        0.2740921 ,  0.1090954 ,  0.23720076,  0.16798855,  0.14524807,
        0.29547298,  0.17872478,  0.1868581 ,  0.26997531,  0.1213415 ,
        0.11450153,  0.18731348,  0.13389003,  0.1689034 ,  0.25231974,
        0.22145248,  0.16671255,  0.12548695,  0.13673749,  0.10741922,
        0.19501032,  0.11232471,  0.25094955,  0.18285807,  0.17503094,
        0.16747859,  0.04932688,  0.34028849,  0.22644909,  0.25969091,
        0.05386681,  0.18633318,  0.22897398,  0.17602516,  0.09917961,
        0.19413067,  0.12741055,  0.23735711,  0.07367315,  0.26617052,
       -0.06441242,  0.10266445,  0.11889974,  0.18753141,  0.11741526,
        0.37361472,  0.26349334,  0.2622499 ,  0.19886521,  0.35829201,
        0.18661236,  0.26200378,  0.08781059,  0.10601384,  0.0888808 ,
        0.35237541,  0.25029947,  0.11358172,  0.14949368,  0.11140512,
        0.14625389,  0.28535831,  0.06779243,  0.05025399,  0.21188178,
        0.10538306,  0.27191213,  0.27656545,  0.24707209,  0.13040971,
        0.17055399,  0.0816778 ,  0.21976956,  0.30151392,  0.19244179,
        0.13247461,  0.16102863,  0.07148112,  0.23988592,  0.14571088,
        0.14363391,  0.18479645,  0.41144905,  0.08365555,  0.05366228,
        0.13850394,  0.1910054 ,  0.20537657,  0.16187916,  0.20816522,
        0.13646634,  0.18798087,  0.25392071,  0.13093469,  0.24726856,
        0.17883191,  0.15729204,  0.23877425,  0.3289954 ,  0.21609299,
        0.1740763 ,  0.26728079,  0.11268567,  0.11691749,  0.18647823,
        0.26470646,  0.33638643,  0.20131615,  0.24760613,  0.55279817,
        0.16246793,  0.18776858,  0.19941393,  0.24751815,  0.24943322,
        0.40647008,  0.09624997,  0.13811168,  0.11199429,  0.09581474,
        0.3187815 ,  0.30126276,  0.61410939,  0.15820953,  0.25092585,
        0.12700123,  0.09462785,  0.32822393,  0.22986692,  0.24334756,
        0.24915924,  0.24303503,  0.1260692 ,  0.17718056,  0.14959828,
        0.17053655,  0.26627392,  0.20716131,  0.22771361,  0.13285503,
        0.05726061,  0.24286891,  0.11500913,  0.26511989,  0.1368902 ,
        0.3533276 ,  0.08462471,  0.24317822,  0.15813758,  0.30885535,
        0.21637523,  0.28656787,  0.03290243,  0.07303775,  0.1102075 ,
        0.1013645 ,  0.2359896 ,  0.27267749,  0.02241221,  0.10993322,
        0.09741865,  0.1323691 ,  0.20550466,  0.25469531,  0.21679608,
        0.1587836 ,  0.2363315 ,  0.12328181,  0.39023224,  0.17059827,
        0.25896139,  0.15037356,  0.11480973,  0.15336726,  0.1409921 ,
        0.14658806,  0.2173232 ,  0.24694555,  0.18167678,  0.28594885,
        0.24202165,  0.31157733,  0.22177429,  0.45710586,  0.25123549,
        0.22318319,  0.2269504 ,  0.2022798 ,  0.22684648,  0.10480747,
        0.32396597,  0.23697108,  0.0950916 ,  0.30354929,  0.21788684,
        0.17961705,  0.36009661,  0.06356015,  0.21094545,  0.16780327,
        0.21216946,  0.11724313,  0.12782034,  0.22130377,  0.19637015,
        0.20777299,  0.2338973 ,  0.40900353,  0.47342275,  0.13710589,
        0.2641818 ,  0.21488057,  0.10483376,  0.18603174,  0.12742099,
        0.17561469,  0.17708674,  0.24896371,  0.308148  ,  0.08555675,
        0.26531291,  0.23448869,  0.13080527,  0.16432282,  0.26911202,
        0.15643347,  0.20200376,  0.20782656,  0.30323479,  0.32344638,
        0.14798419,  0.09976527,  0.21743012,  0.23407372,  0.11722885,
        0.11304153,  0.14350619,  0.16839245,  0.87337135,  0.13486645,
        0.25972886,  0.15491338,  0.36530497,  0.29457995,  0.22741323,
        0.3683176 ,  0.2359985 ,  0.12451238,  0.14590503,  0.19389774,
        0.30951301,  0.22975841,  0.3824946 ,  0.41685002,  0.06532215,
        0.24187701,  0.33546807,  0.23086548,  0.3482363 ,  0.06490142,
        0.21117146,  0.00355512,  0.26300641,  0.01256395,  0.35491571,
        0.02059959, -0.01648603,  0.08440231,  0.30106323,  0.2329383 ,
        0.32785566,  0.12997494,  0.05117778,  0.1187205 ,  0.12860737,
        0.20943289,  0.20069674,  0.00938377,  0.25033544,  0.09375585,
        0.0870971 ,  0.18552591,  0.32858404,  0.21538816,  0.21166739,
        0.06662484,  0.33678871,  0.34506561,  0.25974508,  0.26470211,
        0.28819532,  0.1992776 ,  0.16844144,  0.4414145 ,  0.27985664,
        0.26561741,  0.09508145,  0.13972536,  0.17544931,  0.40852789,
        0.23099546,  0.25894734,  0.1385941 ,  0.16394928,  0.18023827,
        0.24010637,  0.24661158,  0.13020825,  0.13725494,  0.31024418,
        0.0868208 ,  0.22313676,  0.27638737,  0.51246432,  0.29482797,
        0.31990518,  0.10955194,  0.17520808,  0.10960888,  0.13339154,
        0.01508841,  0.29184374,  0.24873816,  0.19288576,  0.14379353,
        0.06573545,  0.33727664,  0.26289404,  0.38036029,  0.16359186,
        0.25932072,  0.21747198,  0.09667404,  0.24185148,  0.26495919,
        0.3483077 ,  0.24930673,  0.12657233,  0.16360513,  0.18081493,
        0.14244894,  0.1846048 ,  0.24056963,  0.31368257,  0.0901606 ,
        0.2991119 ,  0.09519577,  0.06479939,  0.10159001,  0.28851558,
        0.2571779 ,  0.1880871 ,  0.08983777,  0.33701142,  0.21180611,
        0.2733805 ,  0.18852132,  0.38643178,  0.12742661,  0.2646881 ,
        0.19530264,  0.1621164 ,  0.13673749,  0.26819682,  0.1592793 ,
        0.19512298,  0.27939483,  0.14502212,  0.08148293,  0.21285261,
        0.16688055,  0.15141951,  0.06539799,  0.20710226,  0.14749424,
        0.21940839,  0.07918922,  0.36362763,  0.21675354,  0.24964989,
        0.29203719,  0.13672974,  0.39746156,  0.13140448,  0.25395953,
        0.13108831,  0.1451436 ,  0.31570246,  0.09160397,  0.03561699,
        0.12554403,  0.32715587,  0.13261691,  0.10571116,  0.21559925,
        0.19627921,  0.28392805,  0.26657455,  0.11373346,  0.13608269])

In [24]:
Y_test

array([0.06540758, 0.07096237, 0.27371198, 0.14165394, 0.20288849,
       0.15970004, 0.17858631, 0.07373976, 0.28482155, 0.0931815 ,
       0.13900847, 0.09040411, 0.18066935, 0.06957367, 0.11706707,
       0.2667685 , 0.2334398 , 0.21191501, 0.17372587, 0.24800722,
       0.19594501, 0.22094154, 0.07235106, 0.21677545, 0.35009027,
       0.10776281, 0.18414109, 0.35852937, 0.09734759, 0.11540064,
       0.17372587, 0.22510762, 0.38203027, 0.27093459, 0.11783086,
       0.06818497, 0.3896681 , 0.35009027, 0.08623802, 0.06263019,
       0.16678239, 0.19177892, 0.22371893, 0.3157617 , 0.337592  ,
       0.14539647, 0.72445633, 0.15289543, 0.11123455, 0.0694348 ,
       0.19661853, 0.22946952, 0.18066935, 0.15220108, 0.30565199,
       0.20149979, 0.20962366, 0.29593112, 0.41674767, 0.25704763,
       0.24802111, 0.06401889, 0.07651715, 0.10498542, 0.1653937 ,
       0.4070268 , 0.1987224 , 0.18469657, 0.16178309, 0.13900847,
       0.13900847, 0.1653937 , 0.07860019, 0.17303152, 0.22094154,
       0.25635328, 0.18761283, 0.14428552, 0.16803222, 0.12651021,
       0.15289543, 0.13623108, 0.21816414, 0.17372587, 0.21191501,
       0.15567282, 0.06749063, 0.3014859 , 0.14248021, 0.22510762,
       0.08054437, 0.17372587, 0.14109152, 0.15428413, 0.13067629,
       0.19654492, 0.1278989 , 0.18761283, 0.1292876 , 0.16955978,
       0.03485627, 0.11748368, 0.13900847, 0.17303152, 0.09873629,
       0.40286071, 0.20136092, 0.33304402, 0.20288849, 0.34036939,
       0.21260936, 0.23621719, 0.13192612, 0.13831412, 0.11401194,
       0.39313984, 0.20719345, 0.13206499, 0.14595195, 0.13720317,
       0.11595612, 0.24718789, 0.10706846, 0.11540064, 0.17914179,
       0.11123455, 0.19316762, 0.31120678, 0.25010415, 0.14595195,
       0.13900847, 0.08137759, 0.11470629, 0.2841272 , 0.18622414,
       0.0931815 , 0.11678933, 0.08207193, 0.22371893, 0.15150674,
       0.14456326, 0.22580197, 0.54154978, 0.06263019, 0.06263019,
       0.15845022, 0.20149979, 0.19386196, 0.11387307, 0.15011804,
       0.12373281, 0.15970004, 0.27093459, 0.11887238, 0.23177336,
       0.25427024, 0.20136092, 0.27093459, 0.27805583, 0.20844327,
       0.15428413, 0.26260242, 0.13067629, 0.10284544, 0.22094154,
       0.27533676, 0.29225108, 0.19177892, 0.27787807, 0.81946952,
       0.18900153, 0.17789196, 0.19025135, 0.22996806, 0.28343286,
       0.34731287, 0.11748368, 0.11123455, 0.16664352, 0.08068324,
       0.29870851, 0.49659769, 0.98611304, 0.11817803, 0.21080405,
       0.09720872, 0.08346063, 0.31537286, 0.22233023, 0.21399806,
       0.18483544, 0.19316762, 0.12512151, 0.18066935, 0.17094848,
       0.19594501, 0.25595056, 0.15150674, 0.1987224 , 0.15706152,
       0.11269268, 0.22635745, 0.11401194, 0.24732676, 0.16469935,
       0.32912096, 0.10012498, 0.22927371, 0.14595195, 0.35425635,
       0.21399806, 0.17928066, 0.10845716, 0.15289543, 0.13831412,
       0.12512151, 0.10706846, 0.27017914, 0.06332454, 0.07860019,
       0.11123455, 0.13761978, 0.15011804, 0.14303569, 0.20705458,
       0.15289543, 0.24871546, 0.15567282, 0.46159422, 0.1278989 ,
       0.21538675, 0.13553673, 0.09290376, 0.14872934, 0.13206499,
       0.14440633, 0.19525066, 0.22233023, 0.14942369, 0.32078878,
       0.26385224, 0.29638661, 0.18761283, 0.59727816, 0.27093459,
       0.1987224 , 0.21052632, 0.18747396, 0.13137064, 0.11678933,
       0.29037634, 0.19004305, 0.13206499, 0.35981114, 0.18122483,
       0.12859325, 0.37022636, 0.09026524, 0.21538675, 0.16122761,
       0.20288849, 0.13053743, 0.17580892, 0.20219414, 0.20288849,
       0.20691571, 0.12095542, 0.47715595, 0.48062769, 0.15150674,
       0.31259547, 0.20948479, 0.14178586, 0.1973337 , 0.14456326,
       0.14178586, 0.17650326, 0.22635745, 0.28065546, 0.04652132,
       0.2667685 , 0.20149979, 0.16053326, 0.14456326, 0.18622414,
       0.13553673, 0.15011804, 0.21538675, 0.337592  , 0.34175809,
       0.20219414, 0.11748368, 0.10081933, 0.17775309, 0.11123455,
       0.14386891, 0.16678239, 0.14595195, 0.17372587, 0.1653937 ,
       0.26399111, 0.19802805, 0.35425635, 0.27371198, 0.13206499,
       0.40286071, 0.23274545, 0.14317456, 0.15567282, 0.20038883,
       0.41674767, 0.2334398 , 0.37092071, 0.41420358, 0.11678933,
       0.23885571, 0.36188446, 0.24163311, 0.33342591, 0.10567977,
       0.16886544, 0.05221497, 0.21538675, 0.06610193, 0.15567282,
       0.02791279, 0.06124149, 0.13275934, 0.30704069, 0.19663936,
       0.2667685 , 0.13553673, 0.09040411, 0.12581586, 0.12512151,
       0.18469657, 0.13900847, 0.02444105, 0.22927371, 0.12998195,
       0.12234412, 0.16678239, 0.26885155, 0.1973337 , 0.16794195,
       0.10220803, 0.31606721, 0.34517845, 0.25010415, 0.12095542,
       0.22927371, 0.18900153, 0.1388696 , 0.52089988, 0.27787807,
       0.18761283, 0.10429107, 0.15970004, 0.19802805, 0.38897375,
       0.21399806, 0.31259547, 0.09720872, 0.16946535, 0.15171782,
       0.25149285, 0.21955284, 0.1278989 , 0.15150674, 0.27371198,
       0.09734759, 0.1813637 , 0.33245383, 0.5993612 , 0.29870851,
       0.28343286, 0.07790585, 0.11401194, 0.06679628, 0.18414109,
       0.03277323, 0.28134981, 0.16955978, 0.10706846, 0.09734759,
       0.12581586, 0.29870851, 0.14039717, 0.47576725, 0.13345369,
       0.27787807, 0.12373281, 0.12234412, 0.17789196, 0.29395639,
       0.34205388, 0.17372587, 0.14248021, 0.14317456, 0.14241078,
       0.11817803, 0.21955284, 0.2207735 , 0.34442716, 0.09734759,
       0.33342591, 0.13623108, 0.10706846, 0.12581586, 0.25010415,
       0.27093459, 0.14595195, 0.07651715, 0.30842938, 0.23899458,
       0.19580614, 0.12164977, 0.42369115, 0.12373281, 0.26121372,
       0.20136092, 0.12859325, 0.14109152, 0.33338425, 0.15150674,
       0.14872934, 0.32787113, 0.14595195, 0.11678933, 0.20552701,
       0.21835856, 0.15115956, 0.0411054 , 0.21052632, 0.17372587,
       0.19316762, 0.11887238, 0.49953756, 0.1594223 , 0.22510762,
       0.21677545, 0.15886682, 0.38203027, 0.11956673, 0.20094431,
       0.13067629, 0.17080961, 0.28482155, 0.10706846, 0.07929454,
       0.14039717, 0.35021525, 0.15289543, 0.06887932, 0.20844327,
       0.19455631, 0.24316067, 0.321622  , 0.14890293, 0.15636717])

In [27]:
#Accracy of model
linear_regression.score(X_test,Y_test)

0.6825983265973221

In [30]:
#k fold cross validation
import numpy as np
from sklearn.model_selection import KFold
linear_regression
kflod_validation=KFold(10)

In [34]:
from sklearn.model_selection import cross_val_score as sc
results=sc(linear_regression,x,y,cv=kflod_validation)
print(results)
print(np.mean(results))

[0.76666015 0.82979843 0.86081925 0.70110168 0.76949442 0.76945646
 0.74996655 0.75073452 0.58088786 0.80069797]
0.7579617282926168

In [35]:
#Leave one our cross validation(LOOCV)